### ISSUE TITLE
Don't do CSS first

### ISSUE THREAD

**Issue by easchwar** [modred11/promulgation.ninja#2]
Your app will change a ton over its lifecycle. Forcing yourself into super specific CSS before you've even fully determined functionality is going to result in a lot of rework. It's probably worth adding CSS to features as you implement them

**Comment by Carl-Maxwell** [comment]
Oh, well, I already did most of the CSS now. I didn't see these issues until just a couple minutes ago.

**Comment by Carl-Maxwell** [comment]
It was the easiest way for me to make the wireframes anyway.

**Comment by Carl-Maxwell** [comment]
Oh, I see, so, you're saying that the first phase shouldn't be CSS. Sorry, I misunderstood.

I guess I'll start working from the model / database level upwards then.
